[project]
name = "sf-backtester"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "polars>=1.37.1",
    "pyyaml>=6.0.3",
    "sf-quant>=0.1.18",
]

[project.scripts]
sf_backtester = "sf_backtester.cli:main"
